---
# ------------------------------------------------------------------------------
# Reusable Tasks (using variables)
# ------------------------------------------------------------------------------
- name: Setup logrotate
  become: "{{ use_become }}"
  ansible.builtin.template:
    src: xray/logrotate.j2
    dest: "{{ xray_logrotate_config }}"

- name: Setup xray config
  become: "{{ use_become }}"
  ansible.builtin.template:
    src: xray/config_client.json.j2
    dest: "{{ xray_config_file }}"

- name: Ensure Xray log directory exists
  become: "{{ use_become }}"
  ansible.builtin.file:
    path: "{{ xray_log_dir }}"
    state: directory
    owner: "{{ xray_log_owner | default(omit) }}"
    group: "{{ xray_log_group | default(omit) }}"
    mode: "0755"
  tags: service

- name: Force log file rotation
  become: "{{ use_become }}"
  command: "{{ xray_logrotate_command }}"
  tags: service

# ------------------------------------------------------------------------------
# Include OS-specific tasks
# ------------------------------------------------------------------------------
- name: Include macOS tasks
  ansible.builtin.include_tasks: macos.yml
  when: ansible_facts['os_family'] == "Darwin"

- name: Include Arch Linux tasks
  ansible.builtin.include_tasks: archlinux.yml
  when: ansible_facts['os_family'] == "Archlinux"
