---
brew_path: >-
  {%- if ansible_facts['os_family'] == 'Darwin' and ansible_facts['architecture'] == 'arm64' -%}
  /opt/homebrew
  {%- elif ansible_facts['os_family'] == 'RedHat' or ansible_facts['os_family'] == 'Debian' -%}
  /home/linuxbrew/.linuxbrew
  {%- else -%}
  /usr/local
  {%- endif -%}

logrotate_config_dir: >-
  {%- if ansible_facts['os_family'] == 'Darwin' -%}
  {{ ansible_env.HOME }}/.config/logrotate.d
  {%- else -%}
  /etc/logrotate.d
  {%- endif -%}

xray_logrotate_config: "{{ logrotate_config_dir }}/xray"

client_apps:
  - xray
