---
openwrt_pass_path: "Network/Home/OpenWrt/ssh"

ansible_host: "{{ lookup('community.general.passwordstore', openwrt_pass_path, subkey='ip') }}"
ansible_user: >-
  {{
    lookup('community.general.passwordstore', openwrt_pass_path, subkey='user')
    | default('root', true)
  }}
ansible_port: "{{ lookup('community.general.passwordstore', openwrt_pass_path, subkey='port') | default(22, true) }}"
ansible_password: "{{ lookup('community.general.passwordstore', openwrt_pass_path) }}"
ansible_python_interpreter: /usr/bin/python3

openwrt_package_mirror: https://mirrors.tuna.tsinghua.edu.cn/openwrt
