[General]
loglevel = info
dns-server = 223.5.5.5, 8.8.8.8
always-real-ip = tracker, apple.com
tun = auto

# Local HTTP CONNECT proxy
interface = 127.0.0.1
port = 1087

# Local SOCKS5 proxy with UDP Associate support
socks-interface = 127.0.0.1
socks-port = 1086

[Proxy]
Direct = direct
Reject = reject

# VMess over WebSocket over TLS (TLS + WebSocket + VMess)
VMessWSS = vmess, chuxubank.top, 443, username=77926c07-efe9-44c6-b848-fa9150d253b1, ws=true, tls=true, ws-path=/ray

[Proxy Group]
# fallback 等效于 failover
Fallback = fallback, VMessWSS, interval=600, timeout=5

[Rule]
# 执行文件目录当中必需有 `site.dat` 文件
EXTERNAL, site:category-ads-all, Reject

IP-CIDR, 8.8.8.8/32, Fallback

EXTERNAL, site:geolocation-!cn, Fallback

EXTERNAL, site:speedtest, Fallback

FINAL, Direct
