[Endpoint]
; tag, parser, parser-specific params...
Direct, builtin, freedom
Reject, builtin, blackhole
Dns-Out, builtin, dns

Proxy-1, vmess1, vmess1://77926c07-efe9-44c6-b848-fa9150d253b1@chuxubank.top:443/ray?network=ws&tls=true&mux=8

[EndpointGroup]
; tag, colon-seperated list of selectors or endpoint tags, strategy, strategy-specific params...
Auto, Proxy-1, latency, interval=300, timeout=6

[Dns]
; hijack = dns endpoint tag
hijack = Dns-Out
; cliengIp = ip
clientIp = 114.114.114.114

[DnsServer]
; address, port, tag
localhost
119.28.28.28
223.5.5.5
8.8.8.8, 53, Remote
8.8.4.4

[DnsRule]
; type, filter, dns server tag
;; Censorship
DOMAIN-KEYWORD, geosite:category-anticensorship, Remote
DOMAIN-KEYWORD, geosite:category-porn, Remote
;; Develop
DOMAIN-KEYWORD, geosite:github, Remote
;; Google
DOMAIN-KEYWORD, geosite:google, Remote

[DnsHost]
; domain = ip
doubleclick.net = 127.0.0.1

[Routing]
domainStrategy = IPIfNonMatch

[RoutingRule]
; type, filter, endpoint tag or enpoint group tag

;; DNS
IP-CIDR, 119.28.28.28/32, Direct
IP-CIDR, 223.5.5.5/32, Direct
IP-CIDR, 8.8.8.8/32, Auto
IP-CIDR, 8.8.4.4/32, Auto

;; Advertisement
DOMAIN-SUFFIX, cbu01.alicdn.com, Direct
DOMAIN-KEYWORD, geosite:category-ads-all, Reject
DOMAIN-SUFFIX, fam-ad.com, Reject

;; Speedup
;; > Github
DOMAIN-KEYWORD, geosite:github, Auto
;; > Apple
DOMAIN-KEYWORD, geosite:apple-dev, Auto
DOMAIN, apps.apple.com, Auto

;; Unblock
;; > NixOS
DOMAIN-KEYWORD, geosite:nixos, Direct
;; > Google
DOMAIN-KEYWORD, geosite:google@cn, Direct
DOMAIN, mtalk.google.com, Direct
;; > Apple
DOMAIN-KEYWORD, geosite:apple, Direct
;; > Microsoft
DOMAIN-KEYWORD, geosite:microsoft@cn, Direct
;; > Amazon
DOMAIN-KEYWORD, geosite:amazon@cn, Direct
;; > Nvidia
DOMAIN-KEYWORD, geosite:nvidia, Direct
;; > Vercel
DOMAIN-KEYWORD, geosite:vercel, Direct
;; > Steam
DOMAIN-KEYWORD, geosite:steam@cn, Direct
;; > UNIQLO
DOMAIN-SUFFIX, uniqlo.com, Direct
;; > Video
DOMAIN-SUFFIX, panopto.com, Direct
;; > yyets
DOMAIN-KEYWORD, geosite:yyets, Direct
;; > China
DOMAIN-KEYWORD, geosite:cn, Direct
;; > Work
DOMAIN-KEYWORD, zhiyan, Direct
;; > Self
DOMAIN-SUFFIX, chuxubank.top, Direct

;; Foreign
DOMAIN-KEYWORD, geosite:geolocation-!cn, Auto

;; IP
GEOIP, cn, Direct
GEOIP, private, Direct

FINAL, Auto
