[General]
;; loglevel = info
dns-server = 223.5.5.5, 8.8.8.8
always-real-ip = tracker, apple.com
tun = auto

# Local HTTP CONNECT proxy
interface = 127.0.0.1
port = 1087

# Local SOCKS5 proxy with UDP Associate support
socks-interface = 127.0.0.1
socks-port = 1086

[Proxy]
Direct = direct
Reject = reject

# VMess over WebSocket over TLS (TLS + WebSocket + VMess)
VMessWSS-CF = vmess, chuxubank.top, 8443, username=30490e90-2f1e-48c9-a33e-04aaf13fa431, ws=true, tls=true, ws-path=/misaka_vmess_ws
VMessWSS = vmess, 74.121.150.27, 8445, username=30490e90-2f1e-48c9-a33e-04aaf13fa431, ws=true, tls=true, ws-path=/misaka_vmess_ws, sni=chuxubank.top

# Trojan over WebSocket over TLS (TLS + WebSocket + Trojan)
Trojan-CF = trojan, chuxubank.top, 8443, password=30490e90-2f1e-48c9-a33e-04aaf13fa431, sni=chuxubank.top, ws=true, ws-path=/misaka_trojan_ws
Trojan = trojan, 74.121.150.27, 8445, password=30490e90-2f1e-48c9-a33e-04aaf13fa431, sni=chuxubank.top, ws=true, tls=true, ws-path=/misaka_trojan_ws

[Proxy Group]
# fallback 等效于 failover
Auto = fallback, Trojan, interval=600, timeout=5

[Rule]
# DNS
IP-CIDR, 119.28.28.28/32, Direct
IP-CIDR, 223.5.5.5/32, Direct
IP-CIDR, 8.8.8.8/32, Auto
IP-CIDR, 8.8.4.4/32, Auto

# Advertisement
DOMAIN-SUFFIX, cbu01.alicdn.com, Direct
EXTERNAL, site:category-ads-all, Reject
DOMAIN-SUFFIX, fam-ad.com, Reject

# Location
DOMAIN-SUFFIX, location.services.mozilla.com, Direct
DOMAIN-SUFFIX, aviationweather.gov, Direct
DOMAIN-SUFFIX, api.met.no, Direct

# Speedup
## Github
EXTERNAL, site:github, Auto
## Apple
EXTERNAL, site:apple-dev, Auto
DOMAIN, apps.apple.com, Auto
## Amazon
DOMAIN-SUFFIX, d3c33hcgiwev3.cloudfront.net, Auto

# Unblock
## Google
# EXTERNAL, site:google@cn, Direct
DOMAIN-SUFFIX, dl.google.com, Direct
DOMAIN-SUFFIX, mtalk.google.com, Direct
## Apple
EXTERNAL, site:apple, Direct
## Microsoft
# EXTERNAL, site:microsoft@cn, Direct
## Amazon
# EXTERNAL, site:amazon@cn, Direct
## Nvidia
EXTERNAL, site:nvidia, Direct
## Vercel
EXTERNAL, site:vercel, Direct
## Steam
# EXTERNAL, site:steam@cn, Direct
## UNIQLO
DOMAIN-SUFFIX, uniqlo.com, Direct
## Docker
EXTERNAL, site:docker, Direct
## Notion
EXTERNAL, site:notion, Direct
## Manjaro
DOMAIN-KEYWORD, manjaro, Direct
## ELPA
DOMAIN-KEYWORD, elpa, Direct
## Book
DOMAIN-SUFFIX, calibre-ebook.com, Direct
## TeXmacs
DOMAIN-SUFFIX, texmacs.org, Direct
## GNOME
DOMAIN-SUFFIX, gnome.org, Direct
## jetbrain
DOMAIN-SUFFIX, plugins.jetbrains.com, Direct

# China
EXTERNAL, site:cn, Direct
## CNPM
DOMAIN-SUFFIX, cnpmjs.org, Direct
## Work
DOMAIN-KEYWORD, zhiyan, Direct
## Self
DOMAIN-SUFFIX, chuxubank.top, Direct
## Oray
DOMAIN-SUFFIX, oray.net, Direct
## eoffcn
DOMAIN-SUFFIX, eoffcn.com, Direct

# CDN
## Amazon
DOMAIN-SUFFIX, cloudfront.net, Direct
## Gradle
DOMAIN-SUFFIX, downloads.gradle-dn.com, Direct
## Bilibili
DOMAIN-KEYWORD, bilicdn, Direct
DOMAIN-KEYWORD, bilivideo, Direct
DOMAIN-SUFFIX, akamaiedge.net, Direct
DOMAIN-SUFFIX, tdnsv2.com, Direct
## Netease
DOMAIN-SUFFIX, 163jiasu.com, Direct
DOMAIN-SUFFIX, wsglb0.com, Direct

# Foreign
EXTERNAL, site:geolocation-!cn, Auto

# IP
GEOIP, cn, Direct
GEOIP, private, Direct

FINAL, Auto
