[General]
;; loglevel = info
dns-server = 223.5.5.5, 8.8.8.8
always-real-ip = tracker, apple.com
tun = auto

# Local HTTP CONNECT proxy
interface = 127.0.0.1
port = 1087

# Local SOCKS5 proxy with UDP Associate support
socks-interface = 127.0.0.1
socks-port = 1086

[Proxy]
Direct = direct
Reject = reject

# VMess over WebSocket over TLS (TLS + WebSocket + VMess)
VMessWSS = vmess, chuxubank.top, 443, username=77926c07-efe9-44c6-b848-fa9150d253b1, ws=true, tls=true, ws-path=/ray

[Proxy Group]
# fallback 等效于 failover
Auto = fallback, VMessWSS, interval=600, timeout=5

[Rule]
;; DNS
IP-CIDR, 119.28.28.28/32, Direct
IP-CIDR, 223.5.5.5/32, Direct
IP-CIDR, 8.8.8.8/32, Auto
IP-CIDR, 8.8.4.4/32, Auto

;; Advertisement
DOMAIN-SUFFIX, cbu01.alicdn.com, Direct
EXTERNAL, site:category-ads-all, Reject
DOMAIN-SUFFIX, fam-ad.com, Reject

;; Speedup
;; > Github
EXTERNAL, site:github, Auto
;; > Apple
EXTERNAL, site:apple-dev, Auto
DOMAIN, apps.apple.com, Auto

;; Unblock
;; > NixOS
EXTERNAL, site:nixos, Direct
;; > Google
EXTERNAL, site:google@cn, Direct
DOMAIN, mtalk.google.com, Direct
;; > Apple
EXTERNAL, site:apple, Direct
;; > Microsoft
EXTERNAL, site:microsoft@cn, Direct
;; > Amazon
EXTERNAL, site:amazon@cn, Direct
;; > Nvidia
EXTERNAL, site:nvidia, Direct
;; > Vercel
EXTERNAL, site:vercel, Direct
;; > Steam
EXTERNAL, site:steam@cn, Direct
;; > UNIQLO
DOMAIN-SUFFIX, uniqlo.com, Direct
;; > yyets
EXTERNAL, site:yyets, Direct
;; > China
EXTERNAL, site:cn, Direct
;; > CNPM
DOMAIN-SUFFIX, cnpmjs.org, Direct
;; > Work
DOMAIN-KEYWORD, zhiyan, Direct
;; > Self
DOMAIN-SUFFIX, chuxubank.top, Direct

;; Foreign
EXTERNAL, site:geolocation-!cn, Auto

;; IP
GEOIP, cn, Direct
GEOIP, private, Direct

FINAL, Auto
