---
- name: Setup VPS Proxy
  hosts: vps_group
  roles:
    - common
    - server

- name: Setup Local Proxy
  hosts: local_group
  connection: local
  roles:
    - sing-box_client

- name: Setup Proxmox workloads
  hosts: pve_group
  environment: "{{ proxmox_api_env | default({}) }}"
  roles:
    - pve_openwrt

- name: Setup OpenWrt Proxy Client
  hosts: openwrt_group
  gather_facts: false
  roles:
    - openwrt
    - xray_client
