---
- name: Setup VPS Proxy
  hosts: vps_group
  roles:
    - common
    - server

- name: Setup Local Proxy
  hosts: local_group
  connection: local
  roles:
    - xray_client
    - sing-box_client

- name: Setup Proxmox OpenWrt VM
  hosts: pve_group
  environment: "{{ proxmox_api_env | default({}) }}"
  roles:
    - pve_openwrt
