---
- name: Setup VPS Proxy
  hosts: vps_group
  vars:
    proxy_config_dir: "proxy-config"
  roles:
    - common
    - server

- name: Setup Local Proxy
  hosts: local_group
  connection: local
  become: false
  roles:
    - xray_client
    - sing-box_client
