[Endpoint]
Direct, builtin, freedom, domainStrategy=UseIP
Dns-Out, builtin, dns

Proxy-1, vmess1, vmess1://77926c07-efe9-44c6-b848-fa9150d253b1@chuxubank.top:443?network=ws&tls=true

[RoutingRule]
DOMAIN-KEYWORD, geosite:cn, Direct
GEOIP, cn, Direct
GEOIP, private, Direct
FINAL, Proxy-1

[Dns]
hijack = Dns-Out

[DnsServer]
localhost
8.8.8.8
