---
- name: Ensure sing-box config directory exists
  ansible.builtin.file:
    path: "{{ sing_box_config_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ sing_box_on_openwrt | ternary('root', ansible_facts['user_id']) }}"

- name: Ensure sing-box log directory exists
  become: "{{ (not sing_box_on_openwrt) and (use_become | default(false)) }}"
  ansible.builtin.file:
    path: "{{ sing_box_log_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ ansible_facts['user_id'] }}"
  when: not sing_box_on_openwrt

- name: Ensure logrotate config directory exists
  become: "{{ use_become | default(false) }}"
  ansible.builtin.file:
    path: "{{ logrotate_config_dir }}"
    state: directory
    mode: "0755"
  when: not sing_box_on_openwrt

- name: Setup logrotate
  become: "{{ use_become | default(false) }}"
  ansible.builtin.template:
    src: logrotate.j2
    dest: "{{ sing_box_logrotate_config }}"
    mode: "0644"
  notify:
    - Force sing-box log rotation
  when: not sing_box_on_openwrt

- name: Setup sing-box config
  ansible.builtin.template:
    src: config.json.j2
    dest: "{{ sing_box_config_file }}"
    mode: "0600"
  notify:
    - Force sing-box log rotation
    - Restart sing-box service

- name: Include sing-box install tasks
  ansible.builtin.include_tasks: install.yml
  tags: install
