---
- name: Ensure sing-box config directory exists
  ansible.builtin.file:
    path: "{{ sing_box_config_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ ansible_facts['user_id'] }}"

- name: Ensure sing-box log directory exists
  become: "{{ use_become | default(false) }}"
  ansible.builtin.file:
    path: "{{ sing_box_log_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ ansible_facts['user_id'] }}"

- name: Ensure logrotate config directory exists
  become: "{{ use_become | default(false) }}"
  ansible.builtin.file:
    path: "{{ logrotate_config_dir }}"
    state: directory
    mode: "0755"

- name: Setup logrotate
  become: "{{ use_become | default(false) }}"
  ansible.builtin.template:
    src: logrotate.j2
    dest: "{{ sing_box_logrotate_config }}"
  notify:
    - Force sing-box log rotation

- name: Setup sing-box config
  ansible.builtin.template:
    src: config.json.j2
    dest: "{{ sing_box_config_dir }}/50-config.json"
    mode: "0600"
  notify:
    - Force sing-box log rotation
    - Restart sing-box service

- name: Include sing-box install tasks
  ansible.builtin.include_tasks: install.yml
  tags: install
