---
- name: Ensure sing-box service is enabled and started
  become: "{{ use_become | default(true) }}"
  ansible.builtin.systemd:
    name: sing-box.service
    enabled: true
    state: started
    daemon_reload: true
