sing_box_on_openwrt: "{{ ansible_facts['distribution'] | lower == 'openwrt' }}"
sing_box_config_dir: >-
  {{
    sing_box_on_openwrt
    | ternary('/etc/sing-box', ansible_facts['env']['HOME'] ~ '/.config/sing-box')
  }}
sing_box_config_file: >-
  {{
    sing_box_on_openwrt
    | ternary(sing_box_config_dir ~ '/config.json', sing_box_config_dir ~ '/50-config.json')
  }}
sing_box_log_dir: >-
  {{
    sing_box_on_openwrt
    | ternary('/var/log/sing-box', (log_dir | default('/var/log')) ~ '/sing-box')
  }}
sing_box_logrotate_config: "{{ (logrotate_config_dir | default('/etc/logrotate.d')) }}/sing-box"
sing_box_openwrt_packages:
  - sing-box
sing_box_openwrt_service_name: sing-box
sing_box_install_platform: >-
  {{
    'openwrt'
    if sing_box_on_openwrt
    else ansible_facts['distribution'] | lower | replace(' ', '_')
  }}
sing_box_binary: >-
  {{
    (brew_path ~ '/bin/sing-box')
    if ansible_facts['system'] == 'Darwin'
    else '/usr/bin/sing-box'
  }}
sing_box_service_template: >-
  {{
    {
      'Darwin': 'service.plist.j2',
      'Linux': 'service.systemd.j2'
    }.get(ansible_facts['system'], 'service.conf.j2')
  }}
