---
brew_path: >-
  {%- if ansible_facts['os_family'] == 'Darwin' and ansible_facts['architecture'] == 'arm64' -%}
  /opt/homebrew
  {%- elif ansible_facts['os_family'] == 'RedHat' or ansible_facts['os_family'] == 'Debian' -%}
  /home/linuxbrew/.linuxbrew
  {%- else -%}
  /usr/local
  {%- endif -%}

xray_env:
  ADDRESS: "{{ lookup('community.general.passwordstore', proxy_pass_path, subkey='url') }}"
  DOMAIN: "{{ lookup('community.general.passwordstore', proxy_pass_path, subkey='domain') }}"
  REALITY_PUBLIC_KEY: "{{ lookup('community.general.passwordstore', xray_reality_pass_path, subkey='publicKey') }}"
