ansible_host: "{{ lookup('community.general.passwordstore', proxy_pass_path, subkey='url') }}"
ansible_port: "{{ lookup('community.general.passwordstore', proxy_pass_path, subkey='port') }}"
ansible_password: "{{ lookup('community.general.passwordstore', proxy_pass_path) }}"

proxy_env:
  DOMAIN: "{{ lookup('community.general.passwordstore', proxy_pass_path, subkey='domain') }}"
  EMAIL: "{{ lookup('community.general.passwordstore', proxy_pass_path, subkey='email') }}"
  ACME_CA: "acme-v02.api.letsencrypt.org"
  CF_API_TOKEN: "{{ lookup('community.general.passwordstore', cf_pass_path, subkey='api_token') }}"

xray_env:
  REALITY_PRIVATE_KEY: "{{ lookup('community.general.passwordstore', xray_reality_pass_path, subkey='privateKey') }}"

rss_env:
  RSS_SUB_DOMAIN: rss
  DEFAULT_USER: "{{ lookup('community.general.passwordstore', rss_pass_path, subkey='username') }}"
  ADMIN_EMAIL: "{{ lookup('community.general.passwordstore', rss_pass_path, subkey='email') }}"
  ADMIN_PASSWORD: "{{ lookup('community.general.passwordstore', rss_pass_path) }}"
  ADMIN_API_PASSWORD: "{{ lookup('community.general.passwordstore', rss_api_pass_path) }}"
  DB_TYPE: sqlite
  RSSHUB_SUB_DOMAIN: rsshub

proxy_profile:
