xray_env:
  ADDRESS: "{{ lookup('community.general.passwordstore', proxy_pass_path, subkey='url') }}"
  DOMAIN: "{{ lookup('community.general.passwordstore', proxy_pass_path, subkey='domain') }}"
  ALIAS: "{{ lookup('community.general.passwordstore', proxy_pass_path, subkey='alias') }}"
  CLIENT_ID: "{{ lookup('community.general.passwordstore', xray_client_pass_path) }}"
  REALITY_PORT: "{{ lookup('community.general.passwordstore', xray_reality_pass_path, subkey='port') }}"
  REALITY_TARGET: "{{ lookup('community.general.passwordstore', xray_reality_pass_path, subkey='target') }}"
  REALITY_PRIVATE_KEY: "{{ lookup('community.general.passwordstore', xray_reality_pass_path, subkey='privateKey') }}"
  REALITY_PUBLIC_KEY: "{{ lookup('community.general.passwordstore', xray_reality_pass_path, subkey='publicKey') }}"
  REALITY_SHORT_ID: "{{ lookup('community.general.passwordstore', xray_reality_pass_path, subkey='shortId') }}"
  XHTTP_PORT: 2022
  XHTTP_PATH: "{{ lookup('community.general.passwordstore', xray_xhttp_pass_path) }}"
