include:
  - path: ./rss/compose.yml
  - path: ./rsshub/compose.yml

services:
  caddy:
    container_name: caddy
    image: iarekylew00t/caddy-cloudflare
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - path: .env
      - path: ./rss/.env
        required: false
      - path: ./rsshub/.env
        required: false
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  xray:
    container_name: xray
    image: ghcr.io/xtls/xray-core
    depends_on:
      - caddy
    restart: always
    ports:
      - "${REALITY_PORT}:${REALITY_PORT}"
    expose:
      - "${XHTTP_PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./xray/config.json:/etc/xray/config.json
      - caddy_data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  warp:
    container_name: warp
    image: monius/docker-warp-socks
    privileged: true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    ports:
      - "9091:9091"
    volumes:
      - /lib/modules:/lib/modules
    healthcheck:
      test: ["CMD", "curl", "-f", "https://www.cloudflare.com/cdn-cgi/trace"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  caddy_data:
  caddy_config:
