include:
  - path: ./rss/compose.yml

services:
  caddy:
    container_name: caddy
    image: iarekylew00t/caddy-cloudflare
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/certificates:/data/caddy/certificates/${ACME_CA}-directory
      - ./caddy/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    environment:
      DOMAIN: ${DOMAIN}
      EMAIL: ${EMAIL}
      CF_API_TOKEN: ${CF_API_TOKEN}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  xray:
    container_name: xray
    image: ghcr.io/xtls/xray-core
    depends_on:
      - caddy
    restart: always
    ports:
      - "8443:8443/udp"
      - "8445:8445"
      - "8446:8446"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    expose:
      - "2022"
    volumes:
      - ./xray:/etc/xray
      - ./caddy/certificates/${DOMAIN}/${DOMAIN}.crt:/caddy/certificates/domain.crt
      - ./caddy/certificates/${DOMAIN}/${DOMAIN}.key:/caddy/certificates/domain.key
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  # warp:
  #   container_name: warp-server
  #   image: ghcr.io/xtls/xray-core
  #   restart: unless-stopped
  #   network_mode: host
  #   volumes:
  #     - ./xray/warp.json:/etc/xray/config.json
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "200k"
  #       max-file: "10"

  warp:
    container_name: warp
    image: monius/docker-warp-socks
    privileged: true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    ports:
      - "9091:9091"
    volumes:
      - /lib/modules:/lib/modules
    healthcheck:
      test: ["CMD", "curl", "-f", "https://www.cloudflare.com/cdn-cgi/trace"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  caddy_data:
  caddy_config:
