- name: Install xray dependencies
  become: "{{ use_become | default(true) }}"
  ansible.builtin.package:
    name:
      - xray
      - qrencode
    state: present

- name: Deploy xray systemd unit
  become: "{{ use_become | default(true) }}"
  ansible.builtin.template:
    src: "{{ xray_service_template }}"
    dest: "/etc/systemd/system/xray.service"
    mode: "0644"
  notify:
    - Restart xray service
