---
- name: Ensure xray config directory exists
  ansible.builtin.file:
    path: "{{ xray_config_dir }}"
    state: directory
    mode: "0755"

- name: Generate share text
  ansible.builtin.template:
    src: share.txt.j2
    dest: "{{ xray_config_dir }}/share.txt"

- name: Ensure xray log directory exists
  become: "{{ use_become }}"
  ansible.builtin.file:
    path: "{{ xray_log_dir }}"
    state: directory
    mode: "0755"

- name: Ensure logrotate config directory exists
  become: "{{ use_become }}"
  ansible.builtin.file:
    path: "{{ logrotate_config_dir }}"
    state: directory
    mode: "0755"

- name: Setup logrotate
  become: "{{ use_become }}"
  ansible.builtin.template:
    src: logrotate.j2
    dest: "{{ xray_logrotate_config }}"
  notify:
    - Force xray log rotation

- name: Setup xray config
  ansible.builtin.template:
    src: config.json.j2
    dest: "{{ xray_config_dir }}/99-config.json"
  notify:
    - Force xray log rotation
    - Stop xray service
    - Start xray service

- name: Install xray via Homebrew
  community.general.homebrew:
    name: xray
    state: present
  tags: install
