- name: Force sing-box log rotation
  ansible.builtin.command:
    cmd: "logrotate -f {{ sing_box_logrotate_config }}"
  become: "{{ use_become }}"

- name: Restart sing-box service
  ansible.builtin.include_tasks: "{{ playbook_dir }}/roles/common/tasks/restart_service.yml"
  vars:
    service_name: sing-box
    service_template_content: "{{ lookup('template', sing_box_service_template) }}"
  listen: Restart sing-box service
