---
- name: Install packages via Homebrew
  community.general.homebrew:
    name: "{{ homebrew_packages }}"
    state: "{{ homebrew_state | default('present') }}"
    update_homebrew: "{{ homebrew_update | default(omit) }}"
  environment:
    HOMEBREW_NO_AUTO_UPDATE: "{{ homebrew_no_auto_update | default('1') }}"
  tags: install
