---
- name: Check if Docker is installed
  command: docker --version
  register: docker_installed
  ignore_errors: true
  changed_when: false

- name: Install Docker (only if not installed)
  include_role:
    name: geerlingguy.docker
  when: docker_installed.rc != 0

- name: Ensure rsync is installed
  become: "{{ use_become | default(true) }}"
  ansible.builtin.package:
    name: rsync
    state: present
