---
- name: Restart service via Homebrew
  ansible.builtin.shell: |
    brew services restart {{ service_name }} --file=/dev/stdin <<EOF
    {{ service_template_content }}
    EOF
  when: ansible_facts['system'] == 'Darwin'

- name: Restart service via systemd
  become: "{{ use_become | default(true) }}"
  ansible.builtin.systemd:
    name: "{{ service_name }}.service"
    state: restarted
    daemon_reload: true
  when: ansible_facts['system'] == 'Linux'
