all:
  hosts:
    bwg:
      proxy_pass_path: "Network/Host/BandwagonHost/ssh"
      cf_pass_path: "Network/Host/Cloudflare"

    bwg-cn2-gia:
      proxy_pass_path: "Network/Host/BandwagonHost/CN2/ssh"

    nerd:
      proxy_pass_path: "Network/Host/Racknerd/ssh"

    localhost:
      ansible_connection: local
      proxy_pass_path: "Network/Host/BandwagonHost/ssh"

  children:
    vps_group:
      hosts:
        bwg:
        nerd:
      vars:
        cf_pass_path: "Network/Host/Cloudflare"
        rss_pass_path: "Network/Host/FreshRSS/web"
        rss_api_pass_path: "Network/Host/FreshRSS/api"

    xray_group:
      hosts:
        bwg:
        nerd:
        localhost:
      vars:
        xray_client_pass_path: "Network/Xray/Client/Misaka"
        xray_reality_pass_path: "Network/Xray/Reality"
        xray_xhttp_pass_path: "Network/Xray/XHTTP"

    local_group:
      hosts:
        localhost:
