---
# OS-specific tasks for Arch Linux

- name: Install Xray via Pacman (Arch Linux)
  become: true
  community.general.pacman:
    name: xray
    state: present
  tags: install

- name: Stop Xray service (Arch Linux)
  become: true
  ansible.builtin.systemd:
    name: xray
    state: stopped
  tags: service

- name: Start Xray service (Arch Linux)
  become: true
  ansible.builtin.systemd:
    name: xray
    state: started
    enabled: true
  tags: service
