---
- name: Install Xray via Homebrew (macOS)
  community.general.homebrew:
    name: xray
    state: present
  when: ansible_facts['os_family'] == "Darwin"
  tags: install

- name: Ensure Xray log directory exists (macOS)
  file:
    path: "{{ xray_log_dir }}"
    state: directory
    mode: "0755"
  when: ansible_facts['os_family'] == "Darwin"
  tags: service

- name: Stop Xray service (macOS)
  command: brew services stop xray
  ignore_errors: true
  when: ansible_facts['os_family'] == "Darwin"
  tags: service

- name: Setup logrotate
  ansible.builtin.template:
    src: templates/xray/logrotate.j2
    dest: "{{ xray_logrotate_config }}"

- name: Setup xray config
  ansible.builtin.template:
    src: templates/xray/config_client.json.j2
    dest: "{{ xray_config_dir }}/99-config.json"

- name: Force log file rotation (macOS)
  command: logrotate -f {{ xray_logrotate_config }} -s ~/.config/logrotate.status
  when: ansible_facts['os_family'] == "Darwin"
  tags: service

- name: Start Xray service with custom config (macOS)
  shell: |
    brew services start xray --file=/dev/stdin <<EOF
    {{ lookup('template', 'templates/xray/service.plist.j2') }}
    EOF
  when: ansible_facts['os_family'] == "Darwin"
  tags: service

- name: Generate share text
  ansible.builtin.template:
    src: templates/xray/share.txt.j2
    dest: "{{ xray_config_dir }}/share.txt"
