---
# ------------------------------------------------------------------------------
# Include OS-specific tasks
# ------------------------------------------------------------------------------
- name: Include macOS tasks
  ansible.builtin.include_tasks: macos.yml
  when: ansible_facts['os_family'] == "Darwin"

- name: Include Arch Linux tasks
  ansible.builtin.include_tasks: archlinux.yml
  when: ansible_facts['os_family'] == "Archlinux"